# Generated by Django 4.2.22 on 2025-06-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Power BI Program",
                "verbose_name_plural": "Power BI Programs",
            },
        ),
    ]
