# Generated by Django 4.2.22 on 2025-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0002_alter_program_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="report_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="program",
            name="workspace_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name="program",
            table="program",
        ),
    ]
