<<<<<<< HEAD
# Generated by Django 5.2.2 on 2025-06-13 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2.22 on 2025-06-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> origin/main


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_created_at_remove_user_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_name",
            field=models.CharField(
                help_text="Required. 100 characters or fewer.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="user_id",
            field=models.ForeignKey(
                help_text="The user who created this group.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Required. A valid email address.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Designates whether this user can log in."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 100 characters or fewer.",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterModelTable(
            name="group",
            table="accounts_group",
        ),
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
    ]
