# Generated by Django 4.2.22 on 2025-06-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobScheduler",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=100, unique=True)),
                ("cron_expression", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_time", models.DateTimeField(blank=True, null=True)),
                ("next_run_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program.program",
                    ),
                ),
            ],
        ),
    ]
