# Generated by Django 4.2.22 on 2025-06-10 17:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("program", "0002_alter_program_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobScheduler",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=100, unique=True)),
                (
                    "cron_expression",
                    models.CharField(
                        help_text='Cron expression for scheduling (e.g., "0 0 * * *" for daily at midnight)',
                        max_length=100,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_time", models.DateTimeField(blank=True, null=True)),
                ("next_run_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Select a program to schedule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_jobs",
                        to="program.program",
                        verbose_name="Program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Job",
                "verbose_name_plural": "Scheduled Jobs",
                "db_table": "job_scheduler_jobscheduler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobExecution",
            fields=[
                (
                    "execution_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("is_aborted", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="job_scheduler.jobscheduler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Execution",
                "verbose_name_plural": "Job Executions",
                "ordering": ["-start_time"],
            },
        ),
    ]
