# Generated by Django 4.2.22 on 2025-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobexecution",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="is_aborted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="start_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("aborted", "Aborted"),
                ],
                db_index=True,
                default="running",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobscheduler",
            name="enabled",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="jobscheduler",
            name="job_name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="jobscheduler",
            name="last_run_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobscheduler",
            name="next_run_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterModelTable(
            name="jobexecution",
            table="job_execution",
        ),
        migrations.AlterModelTable(
            name="jobscheduler",
            table="job_scheduler",
        ),
    ]
